spring.application.name=bilca-event
server.port=${PORT:8080}

spring.datasource.url=${ORACLE_DATASOURCE_URL:jdbc:oracle:thin:@localhost:1521/XEPDB1}
spring.datasource.username=${ORACLE_DATASOURCE_USERNAME:event_app}
spring.datasource.password=${ORACLE_DATASOURCE_PASSWORD:change-me}
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=false

server.error.include-message=always
bilca.admin-api-token=${BILCA_ADMIN_API_TOKEN:}
